<template>
  <div v-if="hasContent" class="agent-trace">
    <div v-if="loadedSkills.length" class="agent-trace__skills" title="本次 Agent 运行已加载的 Skill">
      <span class="agent-trace__skills-label">Skills</span>
      <span
        v-for="skill in loadedSkills"
        :key="skill"
        class="agent-trace__skill-pill"
      >
        {{ skill }}
      </span>
    </div>

    <!-- Terminal collapsed summary: replaces the card list with a single
         row + subtitle. Clicking expands it back to show all cards. -->
    <div v-if="terminal && !summaryExpanded" class="agent-trace__summary">
      <button
        type="button"
        class="agent-trace__summary-row"
        @click="summaryExpanded = true"
      >
        <span class="agent-trace__summary-icon" aria-hidden="true">
          <Check v-if="terminal.type === 'run_complete'" class="agent-trace__summary-icon-svg" />
          <Ban v-else-if="terminal.type === 'cancelled'" class="agent-trace__summary-icon-svg" />
          <AlertTriangle v-else class="agent-trace__summary-icon-svg" />
        </span>
        <span class="agent-trace__summary-text">{{ summaryLine }}</span>
        <ChevronDown class="agent-trace__summary-chevron" aria-hidden="true" />
      </button>
      <div class="agent-trace__summary-subtitle">Generated by AI and can make mistakes</div>
    </div>

    <!-- Expanded list: running view, OR terminal view after user expands. -->
    <div v-else class="agent-trace__list">
      <div v-if="terminal" class="agent-trace__summary-row agent-trace__summary-row--expanded">
        <button
          type="button"
          class="agent-trace__summary-collapse"
          @click="summaryExpanded = false"
        >
          <ChevronDown class="agent-trace__summary-chevron agent-trace__summary-chevron--open" aria-hidden="true" />
          <span class="agent-trace__summary-text">{{ summaryLine }}</span>
        </button>
      </div>

      <TraceStepCard
        v-for="card in cards"
        :key="card.stepId"
        :card="card"
        :display-name="toolDisplay.resolve(card.toolName, card.toolInput)"
      />

      <div v-if="running && cards.length === 0" class="agent-trace__placeholder">
        <span class="agent-trace__placeholder-label">思考中</span>
        <span class="agent-trace__placeholder-dots" aria-hidden="true">
          <span /><span /><span />
        </span>
      </div>

      <div v-if="running && props.onCancel" class="agent-trace__actions">
        <button
          type="button"
          class="agent-trace__cancel"
          :disabled="cancelling"
          @click="onCancelClick"
        >
          {{ cancelling ? '正在取消…' : '取消' }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, toRef, watch } from 'vue'
import { AlertTriangle, Ban, Check, ChevronDown } from 'lucide-vue-next'
import type { AgentTraceEvent, TraceSummary } from '@/types/agentTrace'
import { useAgentTraceStream } from '@/composables/useAgentTraceStream'
import { useToolDisplayName, type ToolNameMap } from '@/composables/useToolDisplayName'
import TraceStepCard from './TraceStepCard.vue'

const props = defineProps<{
  events: AgentTraceEvent[]
  running?: boolean
  toolNameMap?: ToolNameMap
  onCancel?: () => void | Promise<void>
}>()

const eventsRef = toRef(props, 'events')
const { cards, running: streamRunning, summary, terminal } = useAgentTraceStream(eventsRef)
const toolDisplay = useToolDisplayName(props.toolNameMap)

// `running` prop wins when explicitly provided; otherwise infer from the
// presence of a terminal event in the stream.
const running = computed(() => {
  if (props.running !== undefined) return props.running && !terminal.value
  return streamRunning.value
})

const hasContent = computed(() => cards.value.length > 0 || running.value || !!terminal.value)

const summaryExpanded = ref(false)

const loadedSkills = computed(() => {
  const names = new Set<string>()
  for (const event of props.events || []) {
    const skills = event.type === 'run_start' || event.type === 'system_notice'
      ? event.loaded_skills
      : undefined
    if (!Array.isArray(skills)) continue
    for (const skill of skills) {
      if (typeof skill === 'string' && skill.trim()) names.add(skill.trim())
    }
  }
  return Array.from(names)
})

const cancelling = ref(false)
watch(terminal, (term: unknown) => {
  if (term) cancelling.value = false
})

async function onCancelClick() {
  if (!props.onCancel || cancelling.value) return
  cancelling.value = true
  try {
    await props.onCancel()
  } catch {
    cancelling.value = false
  }
}

function formatDuration(secs: number | undefined | null): string {
  if (typeof secs !== 'number' || !Number.isFinite(secs)) return '0.0s'
  return `${secs.toFixed(1)}s`
}

const summaryLine = computed(() => {
  const term = terminal.value
  if (!term) return ''
  const s: TraceSummary | null = summary.value
  const toolCalls = s?.tool_call_count ?? 0
  const duration = s?.thought_duration_seconds ?? 0
  if (term.type === 'run_complete') {
    return `Thought for ${formatDuration(duration)} · ${toolCalls} tool calls`
  }
  if (term.type === 'cancelled') {
    return `Cancelled after ${formatDuration(duration)} · ${toolCalls} tool calls`
  }
  return `Failed after ${formatDuration(duration)} · ${toolCalls} tool calls`
})
</script>

<style scoped>
.agent-trace {
  display: flex;
  flex-direction: column;
  gap: 8px;
  font-size: 13px;
  color: var(--el-text-color-primary, #111827);
}

.agent-trace__list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.agent-trace__skills {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 6px;
  padding: 2px 0;
}

.agent-trace__skills-label {
  font-size: 12px;
  color: var(--el-text-color-secondary, #6b7280);
}

.agent-trace__skill-pill {
  display: inline-flex;
  align-items: center;
  max-width: 220px;
  height: 22px;
  padding: 0 8px;
  border-radius: 999px;
  border: 1px solid var(--el-border-color-lighter, #e5e7eb);
  background: var(--el-fill-color-light, #f5f7fa);
  color: var(--el-text-color-regular, #4b5563);
  font-size: 12px;
  line-height: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.agent-trace__summary {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.agent-trace__summary-row {
  display: flex;
  align-items: center;
  gap: 10px;
  width: 100%;
  padding: 10px 12px;
  border-radius: 8px;
  border: 1px solid var(--el-border-color-lighter, #e5e7eb);
  background: var(--el-fill-color-light, #f5f7fa);
  cursor: pointer;
  font: inherit;
  color: inherit;
  text-align: left;
}

.agent-trace__summary-row--expanded {
  background: transparent;
  border: none;
  padding: 0 4px;
}

.agent-trace__summary-collapse {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  background: transparent;
  border: none;
  padding: 4px;
  cursor: pointer;
  color: var(--el-text-color-secondary, #6b7280);
  font: inherit;
}

.agent-trace__summary-icon-svg {
  width: 16px;
  height: 16px;
}

.agent-trace__summary-text {
  flex: 1;
  font-weight: 500;
}

.agent-trace__summary-chevron {
  width: 14px;
  height: 14px;
  transition: transform 0.15s ease;
}

.agent-trace__summary-chevron--open {
  transform: rotate(180deg);
}

.agent-trace__summary-subtitle {
  font-size: 12px;
  color: var(--el-text-color-secondary, #6b7280);
  padding-left: 12px;
}

.agent-trace__placeholder {
  display: flex;
  align-items: center;
  gap: 6px;
  color: var(--el-text-color-secondary, #6b7280);
  font-size: 13px;
  padding: 6px 4px;
}

.agent-trace__placeholder-label {
  font-weight: 500;
}

.agent-trace__placeholder-dots {
  display: inline-flex;
  align-items: center;
  gap: 3px;
}

.agent-trace__placeholder-dots span {
  display: inline-block;
  width: 5px;
  height: 5px;
  border-radius: 50%;
  background-color: currentColor;
  animation: agent-trace-bounce 1.2s ease-in-out infinite;
}

.agent-trace__placeholder-dots span:nth-child(1) { animation-delay: 0s; }
.agent-trace__placeholder-dots span:nth-child(2) { animation-delay: 0.2s; }
.agent-trace__placeholder-dots span:nth-child(3) { animation-delay: 0.4s; }

@keyframes agent-trace-bounce {
  0%, 60%, 100% { transform: translateY(0); opacity: 0.4; }
  30% { transform: translateY(-4px); opacity: 1; }
}

.agent-trace__actions {
  padding: 4px 0;
}

.agent-trace__cancel {
  font-size: 12px;
  padding: 4px 10px;
  border-radius: 6px;
  background: transparent;
  border: 1px solid var(--el-border-color, #d1d5db);
  color: var(--el-text-color-regular, #4b5563);
  cursor: pointer;
}

.agent-trace__cancel:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.agent-trace__cancel:hover:not(:disabled) {
  background: var(--el-fill-color-light, #f5f7fa);
}
</style>
