"""initial_migration

Revision ID: 00a1ab478ed4
Revises: 
Create Date: 2025-09-15 19:30:31.305951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '00a1ab478ed4'
down_revision = None
branch_labels = None
depends_on = None


def table_exists(table_name: str, connection) -> bool:
    """检查表是否存在（兼容 SQLite 和 PostgreSQL）"""
    # 方法1: 使用 SQLAlchemy 的 inspect（最可靠的方法）
    try:
        inspector = inspect(connection)
        tables = inspector.get_table_names()
        if table_name in tables:
            return True
    except Exception:
        pass
    
    # 方法2: 直接 SQL 查询（SQLite）
    try:
        # 对于 SQLite，查询 sqlite_master 表
        result = connection.execute(
            sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name=:table_name"),
            {"table_name": table_name}
        )
        row = result.fetchone()
        if row is not None:
            return True
    except Exception:
        pass
    
    # 方法3: 对于 PostgreSQL，使用 information_schema
    try:
        result = connection.execute(
            sa.text(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_name = :table_name"
            ),
            {"table_name": table_name}
        )
        row = result.fetchone()
        if row is not None:
            return True
    except Exception:
        pass
    
    # 如果所有方法都失败，返回 False（让迁移尝试创建表）
    return False


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查表是否已存在，如果存在则跳过创建
    connection = op.get_bind()
    
    # 先检查表是否存在
    if table_exists('log_records', connection):
        # 表已存在，跳过创建
        return
    
    # 表不存在，创建表（使用 try-except 作为双重保护）
    try:
        op.create_table('log_records',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('original_filename', sa.String(length=255), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('log_type', sa.Enum('STACK', 'OAM_ANTENNA', name='logtype'), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='logstatus'), nullable=False),
        sa.Column('progress', sa.Float(), nullable=False),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.Column('checksum', sa.String(length=64), nullable=True),
        sa.Column('mime_type', sa.String(length=100), nullable=True),
        sa.Column('log_level', sa.Enum('DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL', name='loglevel'), nullable=True),
        sa.Column('metadata_json', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    except (sa.exc.OperationalError, Exception) as e:
        # 捕获所有可能的异常，检查是否是"表已存在"错误
        error_msg = str(e).lower()
        error_type = type(e).__name__.lower()
        
        # 检查各种可能的"表已存在"错误信息
        if any(keyword in error_msg for keyword in [
            'already exists', 
            'duplicate', 
            'table.*exists',
            'table log_records already exists'
        ]) or 'operationalerror' in error_type:
            # 再次确认表是否存在（防止误判）
            if table_exists('log_records', connection):
                # 表确实已存在，这是正常的，忽略错误
                return
        
        # 其他错误，重新抛出
        raise
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查表是否存在，如果存在则删除
    connection = op.get_bind()
    if table_exists('log_records', connection):
        op.drop_table('log_records')
    # ### end Alembic commands ###
