"""initial_migration

Revision ID: 00a1ab478ed4
Revises: 
Create Date: 2025-09-15 19:30:31.305951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '00a1ab478ed4'
down_revision = None
branch_labels = None
depends_on = None


def table_exists(table_name: str, connection) -> bool:
    """检查表是否存在（兼容 SQLite 和 PostgreSQL）"""
    try:
        inspector = inspect(connection)
        return table_name in inspector.get_table_names()
    except Exception:
        # 如果 inspect 失败，尝试直接查询（SQLite）
        try:
            result = connection.execute(
                sa.text(f"SELECT name FROM sqlite_master WHERE type='table' AND name='{table_name}'")
            )
            return result.fetchone() is not None
        except Exception:
            # 对于 PostgreSQL，使用 information_schema
            try:
                result = connection.execute(
                    sa.text(
                        "SELECT table_name FROM information_schema.tables "
                        f"WHERE table_schema = 'public' AND table_name = '{table_name}'"
                    )
                )
                return result.fetchone() is not None
            except Exception:
                # 如果所有方法都失败，假设表不存在（让迁移继续执行）
                return False


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查表是否已存在，如果存在则跳过创建
    connection = op.get_bind()
    if not table_exists('log_records', connection):
        op.create_table('log_records',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('original_filename', sa.String(length=255), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('log_type', sa.Enum('STACK', 'OAM_ANTENNA', name='logtype'), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='logstatus'), nullable=False),
        sa.Column('progress', sa.Float(), nullable=False),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.Column('checksum', sa.String(length=64), nullable=True),
        sa.Column('mime_type', sa.String(length=100), nullable=True),
        sa.Column('log_level', sa.Enum('DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL', name='loglevel'), nullable=True),
        sa.Column('metadata_json', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查表是否存在，如果存在则删除
    connection = op.get_bind()
    if table_exists('log_records', connection):
        op.drop_table('log_records')
    # ### end Alembic commands ###
