"""add_task_fields_to_log_records

Revision ID: 0b702bf57b40
Revises: b01cb9352b5e
Create Date: 2025-09-15 19:50:28.030405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b702bf57b40'
down_revision = 'b01cb9352b5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new task-related fields to log_records table
    op.add_column('log_records', sa.Column('task_id', sa.String(length=255), nullable=True, comment='Celery任务ID'))
    op.add_column('log_records', sa.Column('retry_count', sa.Integer(), nullable=False, default=0, comment='重试次数'))
    op.add_column('log_records', sa.Column('processing_started_at', sa.DateTime(), nullable=True, comment='处理开始时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the task-related fields
    op.drop_column('log_records', 'processing_started_at')
    op.drop_column('log_records', 'retry_count')
    op.drop_column('log_records', 'task_id')
    # ### end Alembic commands ###
