"""add_task_fields_to_log_records

Revision ID: 0b702bf57b40
Revises: b01cb9352b5e
Create Date: 2025-09-15 19:50:28.030405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b702bf57b40'
down_revision = 'b01cb9352b5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new task-related fields to log_records table
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_columns = {col["name"] for col in inspector.get_columns("log_records")}

    if "task_id" not in existing_columns:
        op.add_column(
            "log_records",
            sa.Column("task_id", sa.String(length=255), nullable=True, comment="Celery任务ID"),
        )
    if "retry_count" not in existing_columns:
        # server_default keeps existing rows valid in SQLite when adding NOT NULL columns.
        op.add_column(
            "log_records",
            sa.Column(
                "retry_count",
                sa.Integer(),
                nullable=False,
                server_default=sa.text("0"),
                comment="重试次数",
            ),
        )
    if "processing_started_at" not in existing_columns:
        op.add_column(
            "log_records",
            sa.Column(
                "processing_started_at",
                sa.DateTime(),
                nullable=True,
                comment="处理开始时间",
            ),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the task-related fields
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_columns = {col["name"] for col in inspector.get_columns("log_records")}

    if "processing_started_at" in existing_columns:
        op.drop_column("log_records", "processing_started_at")
    if "retry_count" in existing_columns:
        op.drop_column("log_records", "retry_count")
    if "task_id" in existing_columns:
        op.drop_column("log_records", "task_id")
    # ### end Alembic commands ###
