"""add_performance_indexes

Revision ID: b01cb9352b5e
Revises: 00a1ab478ed4
Create Date: 2025-09-15 19:30:39.778433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01cb9352b5e'
down_revision = '00a1ab478ed4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 添加性能优化索引
    # 1. 日志类型索引 - 用于按类型筛选
    op.create_index('idx_log_records_log_type', 'log_records', ['log_type'])
    
    # 2. 日志级别索引 - 用于按级别筛选
    op.create_index('idx_log_records_log_level', 'log_records', ['log_level'])
    
    # 3. 状态索引 - 用于按状态筛选
    op.create_index('idx_log_records_status', 'log_records', ['status'])
    
    # 4. 创建时间索引 - 用于时间范围查询和排序
    op.create_index('idx_log_records_created_at', 'log_records', ['created_at'])
    
    # 5. 软删除索引 - 用于过滤已删除记录
    op.create_index('idx_log_records_is_deleted', 'log_records', ['is_deleted'])
    
    # 6. 文件名索引 - 用于搜索功能
    op.create_index('idx_log_records_filename', 'log_records', ['filename'])
    
    # 7. 复合索引 - 用于常见的组合查询
    op.create_index('idx_log_records_deleted_created', 'log_records', ['is_deleted', 'created_at'])
    op.create_index('idx_log_records_type_status', 'log_records', ['log_type', 'status'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除添加的索引
    op.drop_index('idx_log_records_type_status', table_name='log_records')
    op.drop_index('idx_log_records_deleted_created', table_name='log_records')
    op.drop_index('idx_log_records_filename', table_name='log_records')
    op.drop_index('idx_log_records_is_deleted', table_name='log_records')
    op.drop_index('idx_log_records_created_at', table_name='log_records')
    op.drop_index('idx_log_records_status', table_name='log_records')
    op.drop_index('idx_log_records_log_level', table_name='log_records')
    op.drop_index('idx_log_records_log_type', table_name='log_records')
    
    # ### end Alembic commands ###
