"""add_performance_indexes

Revision ID: b01cb9352b5e
Revises: 00a1ab478ed4
Create Date: 2025-09-15 19:30:39.778433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01cb9352b5e'
down_revision = '00a1ab478ed4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_indexes = {index["name"] for index in inspector.get_indexes("log_records")}

    # 添加性能优化索引（幂等）
    if 'idx_log_records_log_type' not in existing_indexes:
        op.create_index('idx_log_records_log_type', 'log_records', ['log_type'])
    if 'idx_log_records_log_level' not in existing_indexes:
        op.create_index('idx_log_records_log_level', 'log_records', ['log_level'])
    if 'idx_log_records_status' not in existing_indexes:
        op.create_index('idx_log_records_status', 'log_records', ['status'])
    if 'idx_log_records_created_at' not in existing_indexes:
        op.create_index('idx_log_records_created_at', 'log_records', ['created_at'])
    if 'idx_log_records_is_deleted' not in existing_indexes:
        op.create_index('idx_log_records_is_deleted', 'log_records', ['is_deleted'])
    if 'idx_log_records_filename' not in existing_indexes:
        op.create_index('idx_log_records_filename', 'log_records', ['filename'])
    if 'idx_log_records_deleted_created' not in existing_indexes:
        op.create_index('idx_log_records_deleted_created', 'log_records', ['is_deleted', 'created_at'])
    if 'idx_log_records_type_status' not in existing_indexes:
        op.create_index('idx_log_records_type_status', 'log_records', ['log_type', 'status'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_indexes = {index["name"] for index in inspector.get_indexes("log_records")}

    # 删除添加的索引（幂等）
    if 'idx_log_records_type_status' in existing_indexes:
        op.drop_index('idx_log_records_type_status', table_name='log_records')
    if 'idx_log_records_deleted_created' in existing_indexes:
        op.drop_index('idx_log_records_deleted_created', table_name='log_records')
    if 'idx_log_records_filename' in existing_indexes:
        op.drop_index('idx_log_records_filename', table_name='log_records')
    if 'idx_log_records_is_deleted' in existing_indexes:
        op.drop_index('idx_log_records_is_deleted', table_name='log_records')
    if 'idx_log_records_created_at' in existing_indexes:
        op.drop_index('idx_log_records_created_at', table_name='log_records')
    if 'idx_log_records_status' in existing_indexes:
        op.drop_index('idx_log_records_status', table_name='log_records')
    if 'idx_log_records_log_level' in existing_indexes:
        op.drop_index('idx_log_records_log_level', table_name='log_records')
    if 'idx_log_records_log_type' in existing_indexes:
        op.drop_index('idx_log_records_log_type', table_name='log_records')
    
    # ### end Alembic commands ###
