"""add_download_count_field

Revision ID: dd47fc05bc77
Revises: 0b702bf57b40
Create Date: 2025-09-15 20:18:36.622784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd47fc05bc77'
down_revision = '0b702bf57b40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add download_count column to log_records table
    bind = op.get_bind()
    columns = bind.execute(sa.text("PRAGMA table_info('log_records')")).fetchall()
    has_download_count = any(row[1] == 'download_count' for row in columns)
    if not has_download_count:
        op.add_column('log_records', sa.Column('download_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove download_count column from log_records table
    bind = op.get_bind()
    columns = bind.execute(sa.text("PRAGMA table_info('log_records')")).fetchall()
    has_download_count = any(row[1] == 'download_count' for row in columns)
    if has_download_count:
        op.drop_column('log_records', 'download_count')
    # ### end Alembic commands ###
