"""add_issue_description_field

Revision ID: e8f9a2b3c4d5
Revises: dd47fc05bc77
Create Date: 2025-01-27 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f9a2b3c4d5'
down_revision = 'dd47fc05bc77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add issue_description column to log_records table
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    column_names = {column["name"] for column in inspector.get_columns("log_records")}
    if "issue_description" not in column_names:
        op.add_column(
            "log_records",
            sa.Column("issue_description", sa.Text(), nullable=True, comment="问题描述"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove issue_description column from log_records table
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    column_names = {column["name"] for column in inspector.get_columns("log_records")}
    if "issue_description" in column_names:
        op.drop_column("log_records", "issue_description")
    # ### end Alembic commands ###
