"""add_full_log_type

Revision ID: f1a2b3c4d5e6
Revises: e8f9a2b3c4d5
Create Date: 2024-01-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'e8f9a2b3c4d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add FULL to the LogType enum
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "postgresql":
        op.execute("ALTER TYPE logtype ADD VALUE IF NOT EXISTS 'FULL'")
    else:
        # SQLite and other dialects: recreate the check constraint via batch_alter_table
        old_enum = sa.Enum('STACK', 'OAM_ANTENNA', name='logtype', native_enum=False)
        new_enum = sa.Enum('STACK', 'OAM_ANTENNA', 'FULL', name='logtype', native_enum=False)
        with op.batch_alter_table('log_records') as batch_op:
            batch_op.alter_column(
                'log_type',
                existing_type=old_enum,
                type_=new_enum,
                existing_nullable=False,
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values directly
    # This would require recreating the enum type and updating all references
    pass
    # ### end Alembic commands ###
