"""add_full_log_type

Revision ID: f1a2b3c4d5e6
Revises: e8f9a2b3c4d5
Create Date: 2024-01-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'e8f9a2b3c4d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add FULL to the LogType enum
    op.execute("ALTER TYPE logtype ADD VALUE 'FULL'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values directly
    # This would require recreating the enum type and updating all references
    pass
    # ### end Alembic commands ###